### ISSUE TITLE
Support the Rancher Charts

### ISSUE THREAD

**Issue by k-ebu** [acryldata/datahub-helm#130]
**Is your feature request related to a problem? Please describe.**
We use [Rancher](https://rancher.com/) to deploy DataHub.  
Rancher has [Rancher Charts](https://www.rancher.co.jp/docs/rancher/v2.x/en/catalog/custom/creating/#chart-types) that is extension of Helm charts. 
Using Rancher Charts, we can edit (overwrite) `values.yaml` from the UI.

**Describe the solution you'd like**
To support the Rancher Charts, we need to add `questions.yaml` and `app-readme.md`.  
And I created these files for `datahub` chart. Please refer to Additional context. 
I will create these for `prerequisites` chart.

**Describe alternatives you've considered**
n/a

**Additional context**
This is the screenshot of Rancher UI.  
Users can set the values when launch or upgrade App.  
Also, it is possible to specify a private registry (like `registry.local`) in an air-gap environment for the `Image Registry`.

![image](https://user-images.githubusercontent.com/106501664/173528858-d90b4923-cc67-4fe4-b9ac-ef7e3c34d534.png)

sample of `questions.yaml`: 

```yaml
---
categories:
  - datahub
  - datacatalog
questions:
  - variable: datahub-gms.enabled
    default: true
    type: boolean
    label: Enable GMS
    group: "datahub-gms"
    description: "Enable GMS"
    show_subquestion_if: true
    subquestions:
      - variable: datahub-gms.image.registry
        required: true
        default: "docker.io"
        type: string
        label: datahub-gms Image Registry
        group: "datahub-gms"
        description: "Image registry for datahub-gms"
      - variable: datahub-gms.image.repository
        required: true
        default: "linkedin/datahub-gms"
        type: string
        label: datahub-gms Image Repository
        group: "datahub-gms"
        description: "Image repository for datahub-gms"
      - variable: datahub-gms.image.tag
        required: true
        default: "v0.8.38"
        type: string
        label: datahub-gms Image Tag
        group: "datahub-gms"
        description: "Image tag for datahub-gms"
  - variable: datahub-frontend.enabled
    default: true
    type: boolean
    label: Enable Frontend
    group: "datahub-frontend"
    description: "Enable Frontend"
    show_subquestion_if: true
    subquestions:
      - variable: datahub-frontend.image.registry
        required: true
        default: "docker.io"
        type: string
        label: datahub-frontend Image Registry
        group: "datahub-frontend"
        description: "datahub-frontend Image Registry"
      - variable: datahub-frontend.ingress.enabled
        default: false
        type: boolean
        label: datahub-frontend Ingress
        group: "datahub-frontend"
        description: "Set up ingress to expose react front-end"
  - variable: acryl-datahub-actions.enabled
    default: true
    type: boolean
    label: Enable Actions
    group: "acryl-datahub-actions"
    description: "Enable Actions"
    show_subquestion_if: true
    subquestions:
      - variable: acryl-datahub-actions.image.registry
        required: true
        default: "docker.io"
        type: string
        label: acryl-datahub-actions Image Registry
        group: "acryl-datahub-actions"
        description: "acryl-datahub-actions Image Registry"
      - variable: acryl-datahub-actions.image.repository
        required: true
        default: "public.ecr.aws/datahub/acryl-datahub-actions"
        type: string
        label: acryl-datahub-actions Image Repository
        group: "acryl-datahub-actions"
        description: "Image repository for acryl-datahub-actions"
      - variable: acryl-datahub-actions.image.tag
        required: true
        default: "v0.0.1-beta.13"
        type: string
        label: acryl-datahub-actions Image Tag
        group: "acryl-datahub-actions"
        description: "Image tag for acryl-datahub-actions"
...
```
