### ISSUE TITLE
Helm dependency is broken

### ISSUE THREAD

**Issue by korjavin** [acryldata/datahub-helm#144]
**Describe the bug**
>helm dependency update ./prerequisites 
generates error
```
Error: can't get a valid version for repositories mysql, kafka. Try changing the version constraint in Chart.yaml
```

**To Reproduce**
- Checkout master branch of this repo
- Run helm dependency update ./prerequisites
- 
**Expected behavior**
Get all the dependencies

**Comment by chgl** [comment]
I believe this might have been a consequence of https://github.com/bitnami/charts/issues/10833 and should be resolved now due to sub-chart dependency updates in the meantime. Running `helm dep update ./prerequisites` seems to work now.

**Comment by korjavin** [comment]
What should I do? Update something?

```
Getting updates for unmanaged Helm repositories...
....
Error: can't get a valid version for repositories mysql, kafka. Try changing the version constraint in Chart.yaml
```

**Comment by chgl** [comment]
@korjavin is the error still happening to you on the current master? I've not been able to reproduce it there.

**Comment by chgl** [comment]
Strange, can't reproduce that locally unfortunately. I can only reproduce it by explicitly setting the version of those dependencies to ones that were purged, e.g.:

```yaml
  - name: mysql
    version: 7.0.0                                                                         # <----- here
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  # This chart deploys an enterprise version of kafka that requires commercial license
  # Note, Schema registry and kafka rest proxy do not require the commercial license
  - name: cp-helm-charts
    version: 0.6.0
    repository: https://confluentinc.github.io/cp-helm-charts/
    condition: cp-helm-charts.enabled
  # This chart deploys a community version of kafka
  - name: kafka
    version: 13.0.0                                                                        # <----- here 
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
```

`Error: can't get a valid version for repositories mysql, kafka. Try changing the version constraint in Chart.yaml`

But with the actual versions it works fine. Maybe try running `helm repo update` beforehand - not sure if `helm dep update` does that implicitly anyway.
