### ISSUE TITLE
DataHub frontend Ingress - HTTP 1.0 client does not support chunked response

### ISSUE THREAD

**Issue by tomasfabian** [acryldata/datahub-helm#167]
**Is your feature request related to a problem? Please describe.**
Behind the scenes we have a VMWare NSX-T virtual network which is not under our direct control.  We enabled the ingress for the datahub-frontend through the Helm chart in the following way:
```
    datahub-frontend:
      enabled: true
      # Set up ingress to expose react front-end
      ingress:
        enabled: true
        hosts:
          - host: datahub.my-dev.online.net
            paths: ["/"]
```

but we are receiving the following exception messages in the datahub-frontend logs:
_play.core.server.common.ServerResultException: HTTP 1.0 client does not support chunked response_

The site can be reached only through the LoadBalancer in our case.

**Describe the solution you'd like**
We would like to be able to define the used HTTP version via the Helm chart.

Or is there another way how to create a "workaround" for our issue, please?

Thank you very much in advance!

Regards Tomas.
