### ISSUE TITLE
Elastic security/auth issue

### ISSUE THREAD

**Issue by jonnywray** [acryldata/datahub-helm#17]
Hi

trying to get up an instance using Elastic as the graph service but getting the following exception in the GMS pod.

```
Caused by: org.elasticsearch.ElasticsearchStatusException: method [HEAD], host [http://datahub-elastic-es-http:9200], URI [/graph_service_v1?ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false], status line [HTTP/1.1 401 Unauthorized]
```

my global values for Elastic are below, and addition of the auth section was enough to get the elastic start up job to work.

```
global:
      graph_service_impl: elasticsearch

      elasticsearch:
        host: "datahub-elastic-es-http"
        port: "9200"
        auth:
          username: elastic
          password:
            secretRef: datahub-elastic-es-elastic-user
            secretKey: elastic
```

Any thoughts?
Thanks a lot

Jonny
