### ISSUE TITLE
Helm upgrade fails when using hostAliases in crons

### ISSUE THREAD

**Issue by nvillarrealjc** [acryldata/datahub-helm#200]
**Describe the bug**
When trying to specify `hostAliases` in crons, I cannot upgrade. Am I doing something incorrect or is there a bug in the way the file is being interpreted? Following the documentation found here: https://github.com/acryldata/datahub-helm/tree/master/charts/datahub/subcharts/datahub-ingestion-cron

```yaml
datahub-ingestion-cron:
  enabled: true
  image:
    repository: acryldata/datahub-ingestion
    tag: "v0.9.2"
  crons:
    my-cron:
      hostAliases:
        - ip: "10.50.1.200"
          hostnames:
            - "example.com"
```

```
helm upgrade --install datahub datahub/datahub --values datahub-values.yaml
Error: UPGRADE FAILED: template: datahub/charts/datahub-ingestion-cron/templates/cron.yaml:30:27: executing "datahub/charts/datahub-ingestion-cron/templates/cron.yaml" at <include "common.tplvalues.render" (dict "value" .hostAliases "context" $)>: error calling include: template: no template "common.tplvalues.render" associated with template "gotpl"
```

**Expected behavior**
Expect upgrade to work
