### ISSUE TITLE
Kafka prerequisite has hardcoded release-name

### ISSUE THREAD

**Issue by ragerin** [acryldata/datahub-helm#222]
**Describe the bug**
Deployment fails when deploying `prerequisites` with a release name other than `prerequisites`, because it is hardcoded in the values-file:
https://github.com/acryldata/datahub-helm/blob/datahub-prerequisites-0.0.12/charts/prerequisites/values.yaml#L70

```
cp-helm-charts:
  # Schema registry is under the community license
  cp-schema-registry:
    enabled: true
    kafka:
      bootstrapServers: "prerequisites-kafka:9092"  # <<release-name>>-kafka:9092
```

The schema registry fails with the error:
```
Couldn't resolve server prerequisites-kafka:9092 from bootstrap.servers as DNS resolution failed for prerequisites-kafka
```

**To Reproduce**
- Deploy the prerequisites helm-chart with another release name than `prerequisuites`.
- Watch the schema registry log.

**Expected behavior**
The chart should by default use the Helm release name, instead of it being hardcoded.
