### ISSUE TITLE
On Adding OIDC Config , Helm chart errors out

### ISSUE THREAD

**Issue by amit-va** [acryldata/datahub-helm#24]
how to reproduce - 

```yaml 
datahub-frontend:
...
  extraEnvs:
    - name: AUTH_OIDC_ENABLED
      value: true
    - name: AUTH_OIDC_CLIENT_ID
      value: "<change-me>"
    - name: AUTH_OIDC_CLIENT_SECRET
      value: "<change-me>"
    - name: AUTH_OIDC_DISCOVERY_URI
      value: "<change-me>"
    - name: AUTH_OIDC_BASE_URL
      value: "<change-me>"
```

```bash 
helm install datahub datahub/datahub --values ./charts/datahub/values.yaml -n datahub

Error: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found t, error found in #10 byte of ...|,"value":true},{"nam|..., bigger context ...|geEvent_v1"},{"name":"AUTH_OIDC_ENABLED","value":true},{"name":"AUTH_OIDC_CLIENT_ID","value":"f8bcbc|...
```

i believe , [toYaml loosing double quote](https://github.com/helm/helm/issues/4262) to be the issue 

https://github.com/acryldata/datahub-helm/blob/master/charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml#L141
