### ISSUE TITLE
Error on nocode-migration post-job

### ISSUE THREAD

**Issue by justmike1** [acryldata/datahub-helm#263]
**Describe the bug**
Getting the error 
```(shell)
2023-02-12 10:21:53.117 ERROR 1 --- [pool-9-thread-1] c.d.authorization.DataHubAuthorizer      : Failed to retrieve policy urns! 
Skipping updating policy cache
```
My values:
```yaml
datahub:
  fullnameOverride: datahub
  global: 
    sql:
      datasource:
        password:
          value: datahub
  neo4j:
    password:
      value: datahub
  datahub-gms:
    fullnameOverride: datahub-datahub-gms
    service:
      type: ClusterIP
  datahub-frontend:
    fullnameOverride: datahub-datahub-frontend
    service:
      type: ClusterIP
    # currently being tested, might change
    resources:
      limits:
        memory: 3000Mi
      requests:
        cpu: 256m
        memory: 1800Mi
  datahub-mae-consumer:
    fullnameOverride: datahub-datahub-mae-consumer
  datahub-mce-consumer:
    fullnameOverride: datahub-datahub-mce-consumer
  acryl-datahub-actions:
    fullnameOverride: datahub-acryl-datahub-actions
```

**Expected behavior**
That it wont fail or proper error

**Screenshots**
![image](https://user-images.githubusercontent.com/90835468/218305632-e378e8e4-d469-44c9-8a1e-263b01b46079.png)

**Additional context**
This issue occurred after upgrading to 0.2.150
