### ISSUE TITLE
Support more SQL options for GMS service

### ISSUE THREAD

**Issue by atul-chegg** [acryldata/datahub-helm#284]
**Describe the bug**
We are using datahub-helm using terraform. We get the following error when we tries to update GMS service.
```
Error: cannot patch "datahub-datahub-gms" with kind Deployment: The order in patch list:
│ [map[name:DATAHUB_REVISION value:12] map[name:EBEAN_DATASOURCE_USERNAME value:test/datahub/mysql/datahub-db/datahub] map[name:EBEAN_DATASOURCE_HOST value:<redacted>:3306] map[name:EBEAN_DATASOURCE_URL value:<redacted>] map[name:EBEAN_DATASOURCE_URL value:jdbc-secretsmanager:mysql://<redacted>/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8&enabledTLSProtocols=TLSv1.2] map[name:EBEAN_DATASOURCE_DRIVER value:com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver] map[name:EBEAN_DATASOURCE_DRIVER value:com.mysql.cj.jdbc.Driver]]
│  doesn't match $setElementOrder list:
│ [map[name:DATAHUB_UPGRADE_HISTORY_KAFKA_CONSUMER_GROUP_ID] map[name:DATAHUB_REVISION] map[name:ENABLE_PROMETHEUS] map[name:ENTITY_REGISTRY_CONFIG_PATH] map[name:DATAHUB_ANALYTICS_ENABLED] map[name:EBEAN_DATASOURCE_USERNAME] map[name:EBEAN_DATASOURCE_PASSWORD] map[name:EBEAN_DATASOURCE_HOST] map[name:EBEAN_DATASOURCE_URL] map[name:EBEAN_DATASOURCE_DRIVER] map[name:KAFKA_BOOTSTRAP_SERVER] map[name:KAFKA_SCHEMAREGISTRY_URL] map[name:SCHEMA_REGISTRY_TYPE] map[name:ELASTICSEARCH_HOST] map[name:ELASTICSEARCH_PORT] map[name:SKIP_ELASTICSEARCH_CHECK] map[name:ELASTICSEARCH_USE_SSL] map[name:GRAPH_SERVICE_IMPL] map[name:SPRING_KAFKA_PROPERTIES_KAFKASTORE_SECURITY_PROTOCOL] map[name:SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL] map[name:SPRING_KAFKA_PROPERTIES_SSL_PROTOCOL] map[name:METADATA_CHANGE_EVENT_NAME] map[name:FAILED_METADATA_CHANGE_EVENT_NAME] map[name:METADATA_AUDIT_EVENT_NAME] map[name:DATAHUB_USAGE_EVENT_NAME] map[name:METADATA_CHANGE_PROPOSAL_TOPIC_NAME] map[name:FAILED_METADATA_CHANGE_PROPOSAL_TOPIC_NAME] map[name:METADATA_CHANGE_LOG_VERSIONED_TOPIC_NAME] map[name:METADATA_CHANGE_LOG_TIMESERIES_TOPIC_NAME] map[name:PLATFORM_EVENT_TOPIC_NAME] map[name:DATAHUB_UPGRADE_HISTORY_TOPIC_NAME] map[name:METADATA_SERVICE_AUTH_ENABLED] map[name:DATAHUB_TOKEN_SERVICE_SIGNING_KEY] map[name:DATAHUB_TOKEN_SERVICE_SALT] map[name:DATAHUB_SYSTEM_CLIENT_ID] map[name:DATAHUB_SYSTEM_CLIENT_SECRET] map[name:UI_INGESTION_ENABLED] map[name:SECRET_SERVICE_ENCRYPTION_KEY] map[name:UI_INGESTION_DEFAULT_CLI_VERSION] map[name:ELASTICSEARCH_QUERY_MAX_TERM_BUCKET_SIZE] map[name:ELASTICSEARCH_QUERY_EXACT_MATCH_EXCLUSIVE] map[name:ELASTICSEARCH_QUERY_EXACT_MATCH_WITH_PREFIX] map[name:ELASTICSEARCH_QUERY_EXACT_MATCH_FACTOR] map[name:ELASTICSEARCH_QUERY_EXACT_MATCH_PREFIX_FACTOR] map[name:ELASTICSEARCH_QUERY_EXACT_MATCH_CASE_FACTOR] map[name:ELASTICSEARCH_QUERY_EXACT_MATCH_ENABLE_STRUCTURED] map[name:ELASTICSEARCH_SEARCH_GRAPH_TIMEOUT_SECONDS] map[name:ELASTICSEARCH_SEARCH_GRAPH_BATCH_SIZE] map[name:ELASTICSEARCH_SEARCH_GRAPH_MAX_RESULT] map[name:SEARCH_SERVICE_ENABLE_CACHE] map[name:LINEAGE_SEARCH_CACHE_ENABLED] map[name:ELASTICSEARCH_INDEX_BUILDER_MAPPINGS_REINDEX] map[name:ELASTICSEARCH_INDEX_BUILDER_SETTINGS_REINDEX] map[name:ALWAYS_EMIT_CHANGE_LOG] map[name:GRAPH_SERVICE_DIFF_MODE_ENABLED] map[name:EBEAN_DATASOURCE_URL] map[name:EBEAN_DATASOURCE_DRIVER]]
│ 
│ 
│   with helm_release.datahub,
│   on datahub.tf line 139, in resource "helm_release" "datahub":
│  139: resource "helm_release" "datahub" {
│ 
╵
Operation failed: failed running terraform apply (exit 1)
```

Why? It is happening because we are passing datasource information using extra env vars (in datahub-values.yml) for gms service. 
```
extraEnvs:
    - name: EBEAN_DATASOURCE_USERNAME
      value: "test/datahub/mysql/datahub-db/datahub"
    - name: EBEAN_DATASOURCE_PASSWORD
      value: "dummy-pass-not-used"
    - name: EBEAN_DATASOURCE_HOST
      value: "${mysql_server}:3306"
    - name: EBEAN_DATASOURCE_URL
      value: "jdbc-secretsmanager:mysql://${mysql_server}:3306/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8&enabledTLSProtocols=TLSv1.2"
    - name: EBEAN_DATASOURCE_DRIVER
      value: "com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver"
```

**To Reproduce**
Pass EBEAN_DATASOURCE_USERNAME in extraEnvs of GMS service. And then try to update gms service.

**Expected behavior**
GMS service should update without any issue. Our current workaround for this issue is to delete datahub-gms deployment and then deploy it again.
