### ISSUE TITLE
missing datahub-auth-secrets on fresh helm install

### ISSUE THREAD

**Issue by JoranDox** [acryldata/datahub-helm#295]
**Describe the bug**
Missing datahub-auth-secrets on fresh helm install

**To Reproduce**
`helm install prerequisites`
`helm install datahub`

**Expected behavior**
According to https://artifacthub.io/packages/helm/datahub/datahub/0.2.77 (the first thing I could find in google), if not provided, one will be generated (is this not true anymore)?

**Screenshots**
![image](https://user-images.githubusercontent.com/7152733/230322105-9bfa1b5a-7630-489d-89bd-2784a619eb34.png)

**Additional context**
Used to work when deploying helm chart 0.2.143 earlier this year, tried 0.2.161 and downgrading to 0.2.160 but neither work, may try to bisect trying to find out where it went wrong later.

**Comment by JoranDox** [comment]
shitty workaround is running helm chart 0.2.143 first, and then running 0.2.161, which doesn't delete the secret

**Comment by TonyOuyangGit** [comment]
This should still hold true as long as you are still using the `datahub-helm/charts/datahub/values.yaml`, where it has `metadata_service_authentication.provisionSecrets.enabled` set to `true`, and if you have previous helm deployment, you'll need to manually remove the dathaub-upgrade job otherwise the system-update will fail.

**Comment by sabper** [comment]
If global.datahub.systemUpdate is enabled, this is reproduced by the datahub system update job running before the datahub-auth-secret generation.

In the current version of helm chart, this is fixed by setting global.datahub.systemUpdate to false.

It would be nice if helm had a way to make global.datahub.systemUpdate run later than datahub-auth-secret generation, but I haven't found a good way to do it.

**Comment by Santhin** [comment]
Would be a good idea to add annotations to `datahub-auth-secrets` which will install this secret and uninstall in case of `helm uninstall`

```yaml
{{- if .Values.global.datahub.metadata_service_authentication.enabled -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace "datahub-auth-secrets" -}}
{{- $data := $secret.data | default dict -}}
{{- with .Values.global.datahub.metadata_service_authentication.provisionSecrets }}

{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "datahub-auth-secrets"
  annotations:
    "helm.sh/hook": post-delete, pre-install
    "helm.sh/hook-weight": "-6"
type: Opaque
data:
  {{- if .autoGenerate }}
  system_client_secret: {{ get $data "system_client_secret" | default (randAlphaNum 32 | b64enc | quote) }}
  token_service_signing_key: {{ get $data "token_service_signing_key"| default (randAlphaNum 32 | b64enc | quote) }}
  token_service_salt: {{ get $data "token_service_salt" | default (randAlphaNum 32 | b64enc | quote) }}
  {{- else }}
  system_client_secret: {{ .secretValues.secret | b64enc | quote }}
  token_service_signing_key: {{ .secretValues.signingKey | b64enc | quote }}
  token_service_salt: {{ .secretValues.salt | b64enc | quote }}
  {{- end }}

{{- end }}
{{- end -}}
{{- end -}}

```
