### ISSUE TITLE
Get data source username from Kubernetes secret.

### ISSUE THREAD

**Issue by matthewhembree** [acryldata/datahub-helm#308]
**Is your feature request related to a problem? Please describe.**

It would be nice if data source usernames could be taken from a Kubernetes secret similar to how the password can be: https://github.com/acryldata/datahub-helm/blob/09a9063443af0d8d56727864dd52b280c11b568a/charts/datahub/templates/postgresql-setup-job.yml#L63-L67

**Describe the solution you'd like**

Example: Add `valueFrom.secretKeyRef` for the `POSTGRES_USERNAME` environment variable in Helm templates.

Current:
```yaml
          env:
            - name: POSTGRES_USERNAME
              value: {{ .Values.postgresqlSetupJob.username | default .Values.global.sql.datasource.username | quote }}
            - name: POSTGRES_PASSWORD
              {{- $passwordValue := (.Values.postgresqlSetupJob.password).value | default .Values.global.sql.datasource.password.value }}
              {{- if $passwordValue }}
              value: {{ $passwordValue | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: "{{ (.Values.postgresqlSetupJob.password).secretRef | default .Values.global.sql.datasource.password.secretRef }}"
                  key: "{{ (.Values.postgresqlSetupJob.password).secretKey | default .Values.global.sql.datasource.password.secretKey }}"
              {{- end }}
```

Proposed:
```yaml
          env:
            - name: POSTGRES_USERNAME
              {{- $usernameValue := (.Values.postgresqlSetupJob.username).value | default .Values.global.sql.datasource.username.value }}
              {{- if $usernameValue }}
              value: {{ $usernameValue | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: "{{ (.Values.postgresqlSetupJob.username).secretRef | default .Values.global.sql.datasource.username.secretRef }}"
                  key: "{{ (.Values.postgresqlSetupJob.username).secretKey | default .Values.global.sql.datasource.username.secretKey }}"
              {{- end }}
            - name: POSTGRES_PASSWORD
              {{- $passwordValue := (.Values.postgresqlSetupJob.password).value | default .Values.global.sql.datasource.password.value }}
              {{- if $passwordValue }}
              value: {{ $passwordValue | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: "{{ (.Values.postgresqlSetupJob.password).secretRef | default .Values.global.sql.datasource.password.secretRef }}"
                  key: "{{ (.Values.postgresqlSetupJob.password).secretKey | default .Values.global.sql.datasource.password.secretKey }}"
              {{- end }}
```

Repeat for other template instances. I'm currently not sure of all of the places this would need to be done.

**Describe alternatives you've considered**

- Adding a helm post renderer `--post-renderer` for Kustomize patching. [ref](https://helm.sh/docs/topics/advanced/#post-rendering)
- Using a Kyverno policy to mutate the resources (deployments/jobs/etc.). [ref](https://kyverno.io/policies/?policytypes=Deployment%2BJob%2Bmutate%2BPod)

**Additional context**

This is useful for Vault dynamic database secrets engine. [ref](https://developer.hashicorp.com/vault/docs/secrets/databases/postgresql)
used in conjunction with the External Secrets Operator. [ref](https://external-secrets.io/v0.8.1/api/generator/vault/)

Thanks!
