### ISSUE TITLE
Elasticsearch single node config

### ISSUE THREAD

**Issue by mihaitodor** [acryldata/datahub-helm#31]
Thank you for these excellent Helm charts! I noticed that, by default, the prerequisites [`values.yaml`](https://github.com/acryldata/datahub-helm/blob/master/charts/prerequisites/values.yaml) spins up 3 Elasticsearch nodes and was wondering if it would be OK to run this as a single instance for local testing. I was reading through the exposed Elasticsearch chart values [here](https://github.com/elastic/helm-charts/blob/7.9.3/elasticsearch/values.yaml) and I'm not sure I get how the `cluster`, `master`, `data` and `client` fields from [here](https://github.com/acryldata/datahub-helm/blob/ed238aefcd856fa57c85c16d6ad70bdbd177447c/charts/prerequisites/values.yaml#L5-L15) are meant to work, since they don't seem documented in the upstream elasticsearch chart. I'm no Helm expert, though.

I was able to start DataHub with Elasticsearch (with [`graph_service_impl: elasticsearch`](https://github.com/acryldata/datahub-helm/blob/ed238aefcd856fa57c85c16d6ad70bdbd177447c/charts/datahub/quickstart-values-without-neo4j.yaml#L46)) in single instance mode using this config:
```yaml
elasticsearch:
  enabled: true
  replicas: 1
  minimumMasterNodes: 1
  antiAffinity: "soft" # Should allow running on a single Kind node too
```
But I'm quite new to DataHub and I need to figure out if this setup works as expected. For now, the pods seem healthy and I can access the UI.
