### ISSUE TITLE
Default User Credentials

### ISSUE THREAD

**Issue by Seokyun-Ha** [acryldata/datahub-helm#322]
**Is your feature request related to a problem? Please describe.**
On the Dathaub Official documenet, it suggests the create default user credential by hand. 
https://datahubproject.io/docs/authentication/changing-default-credentials/

However, this manual task can be ignored and default Datahub master account's id/pw is too trivial, so Anonymouses or Attackers can easily enter the datahub frontend page. 

**Describe the solution you'd like**
Set default user credentials directly in helm value file, without creating secret manually.

**Describe alternatives you've considered**
The credential can be repalced by `extraEnv` and `lifecycle.postStart`. However, it is environment variable, so it can be revealed as plaintext, and revealed when `helm diff`. Also, this method only support single user id/pw replacing.

```yaml
  extraEnvs:
    - name: DATAHUB_MASTER_PASSWORD
      value: newpassword
  lifecycle:
    # To add a new user to datahub in JAAS config without mounting the user.props file
    postStart:
      exec:
        command: ["/bin/sh", "-c", "echo datahub:$DATAHUB_MASTER_PASSWORD > /datahub-frontend/conf/user.props"]
```

**Additional context**
https://datahubproject.io/docs/authentication/changing-default-credentials/

https://github.com/acryldata/datahub-helm/pull/321
