### ISSUE TITLE
Using the ingress agent to access the datahub-frontend reports a 404 error

### ISSUE THREAD

**Issue by lordk911** [acryldata/datahub-helm#413]
**Describe the bug**

`k8s version : v1.25.6`

```
helm list --namespace datahub
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
datahub         datahub         1               2023-12-19 17:43:00.850431119 +0800 CST deployed        datahub-0.3.19                  0.12.1     
prerequisites   datahub         1               2023-12-19 09:55:22.739958604 +0800 CST deployed        datahub-prerequisites-0.1.6  
```  
**datahub-helm/charts/datahub/values.yaml** 

```
datahub-frontend:
  enabled: true
  image:
    repository: linkedin/datahub-frontend-react
    # tag: "v0.11.0" # # defaults to .global.datahub.version
  resources:
    limits:
      memory: 1400Mi
    requests:
      cpu: 100m
      memory: 512Mi
  # Set up ingress to expose react front-end
  ingress:
    enabled: true
    hosts:
      - host: seal-k8s.datahub.com
        paths: [/]
  defaultUserCredentials:
    # randomAdminPassword: true
    # You can also set specific passwords for default users
    manualValues: |
      datahub:datahub123
    #   initialViewer:manualPassword
  # Optionaly specify service type for datahub-frontend: LoadBalancer, ClusterIP or NodePort, by default: LoadBalancer
  service:
     type: ClusterIP
```

```
kubectl get pods,svc,ingress -n datahub

NAME                                                 READY   STATUS      RESTARTS     AGE
pod/datahub-acryl-datahub-actions-777dd87b6d-8hm4b   1/1     Running     0            58m
pod/datahub-datahub-frontend-6cbd7d89c4-tmjjp        1/1     Running     0            58m
pod/datahub-datahub-gms-7b9f5778f6-6df4q             1/1     Running     0            58m
pod/datahub-datahub-system-update-job-xqpmr          0/1     Completed   0            60m
pod/datahub-elasticsearch-setup-job-xgm9t            0/1     Completed   0            64m
pod/datahub-kafka-setup-job-x4chz                    0/1     Completed   0            64m
pod/datahub-mysql-setup-job-snbjw                    0/1     Completed   0            61m
pod/datahub-nocode-migration-job-n8dds               0/1     Completed   0            58m
pod/elasticsearch-master-0                           1/1     Running     0            8h
pod/elasticsearch-master-1                           1/1     Running     0            8h
pod/elasticsearch-master-2                           1/1     Running     0            8h
pod/prerequisites-kafka-0                            1/1     Running     4 (8h ago)   8h
pod/prerequisites-kafka-1                            1/1     Running     4 (8h ago)   8h
pod/prerequisites-kafka-2                            1/1     Running     4 (8h ago)   8h
pod/prerequisites-mysql-0                            1/1     Running     0            8h
pod/prerequisites-zookeeper-0                        1/1     Running     0            8h
pod/prerequisites-zookeeper-1                        1/1     Running     0            8h
pod/prerequisites-zookeeper-2                        1/1     Running     0            8h

NAME                                       TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)                      AGE
service/datahub-acryl-datahub-actions      ClusterIP   10.96.3.7     <none>        9093/TCP                     58m
service/datahub-datahub-frontend           ClusterIP   10.96.3.71    <none>        9002/TCP,4318/TCP            58m
service/datahub-datahub-gms                ClusterIP   10.96.0.75    <none>        8080/TCP,4318/TCP            58m
service/elasticsearch-master               ClusterIP   10.96.1.159   <none>        9200/TCP,9300/TCP            8h
service/elasticsearch-master-headless      ClusterIP   None          <none>        9200/TCP,9300/TCP            8h
service/prerequisites-kafka                ClusterIP   10.96.0.213   <none>        9092/TCP                     8h
service/prerequisites-kafka-headless       ClusterIP   None          <none>        9092/TCP,9094/TCP            8h
service/prerequisites-mysql                ClusterIP   10.96.2.121   <none>        3306/TCP                     8h
service/prerequisites-mysql-headless       ClusterIP   None          <none>        3306/TCP                     8h
service/prerequisites-zookeeper            ClusterIP   10.96.2.225   <none>        2181/TCP,2888/TCP,3888/TCP   8h
service/prerequisites-zookeeper-headless   ClusterIP   None          <none>        2181/TCP,2888/TCP,3888/TCP   8h

NAME                                                 CLASS    HOSTS                  ADDRESS   PORTS   AGE
ingress.networking.k8s.io/datahub-datahub-frontend   <none>   seal-k8s.datahub.com             80      58m
```

```
kubectl describe ingress.networking.k8s.io/datahub-datahub-frontend -n datahub

Name:             datahub-datahub-frontend
Labels:           app.kubernetes.io/instance=datahub
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=datahub-frontend
                  app.kubernetes.io/version=v0.11.0
                  helm.sh/chart=datahub-frontend-0.2.151
Namespace:        datahub
Address:          
Ingress Class:    <none>
Default backend:  <default>
Rules:
  Host                  Path  Backends
  ----                  ----  --------
  seal-k8s.datahub.com  
                        /   datahub-datahub-frontend:9002 (10.0.3.222:9002)
Annotations:            meta.helm.sh/release-name: datahub
                        meta.helm.sh/release-namespace: datahub
Events:                 <none>
```

**when try to access:** 

![image](https://github.com/acryldata/datahub-helm/assets/19989300/dc5e40fa-5607-4435-8104-0a942fad8738)

**To Reproduce**
1. helm install datahub datahub/datahub --values /root/datahub-helm/charts/datahub/values.yaml --namespace datahub --timeout 30m0s

**Expected behavior**
Is there something wrong with my configuration?
