### ISSUE TITLE
Datahub Frontend: OIDC username claim only changable for google 

### ISSUE THREAD

**Issue by gschuurman** [acryldata/datahub-helm#414]
**Describe the bug**
`oidcAuthentication.user_name_claim` is only evaluated with `oidcAuthentication.provider: "google"`
This causes issues for azure ad implementations

**To Reproduce**
Deploy datahub with `oidcAuthentication.provider: "azure"` and `oidcAuthentication.user_name_claim: "preferred_username"`
Observe in the logging that email is still being used as email claim

**Expected behavior**
Expected that preferred_username was used as an email

**Screenshots**
<img width="907" alt="image" src="https://github.com/acryldata/datahub-helm/assets/12977799/5c2ca3cc-4e06-4209-acdb-a417e7f5313a">

**Additional context**
Issue lies with the assignment of the AUTH_OIDC_USER_NAME_CLAIM, this is only set with google
https://github.com/acryldata/datahub-helm/blob/ceb3a26ef9f8c2275de4438c46952697d011952b/charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml#L223 

``` yaml
           {{- if eq .provider "google" }}
            - name: AUTH_OIDC_DISCOVERY_URI
              value: https://accounts.google.com/.well-known/openid-configuration
            - name: AUTH_OIDC_SCOPE
              value: {{ .scope | default "openid profile email" }}
            - name: AUTH_OIDC_USER_NAME_CLAIM
              value: {{ .user_name_claim | default "email" }}
            - name: AUTH_OIDC_USER_NAME_CLAIM_REGEX
              value: {{ .user_name_claim_regex | default "([^@]+)" }}
```
