### ISSUE TITLE
How do I annotate the service accounts for workload id?

### ISSUE THREAD

**Issue by red8888** [acryldata/datahub-helm#440]
In order to use workload id I need to annotate the k8s service account like this:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: workload-identity@{project}.iam.gserviceaccount.com
```

I don't generate json keys for my workloads I use workload id.

How can I annotate the right ServiceAccount to hook them up to a google service account?

I also see lots of service accounts: https://github.com/search?q=repo%3Aacryldata%2Fdatahub-helm%20kind%3A%20serviceaccount&type=code

Which one do I annotate to give the big query connector access?
