### ISSUE TITLE
Neither global.sql.datasource.username.secretRef/Key nor *SetupJob.username.secretRef/Key work

### ISSUE THREAD

**Issue by megri** [acryldata/datahub-helm#531]
**Describe the bug**
Using chart version 0.4.39 which is latest version at the time of writing.

When setting *any* `*.username.secretRef/secretKey` the chart won't build properly and errors out with
```
Error: could not merge values: wrong node kind: expected ScalarNode but got MappingNode: node contents:
secretKey: bar
secretRef: foo
```

**To Reproduce**
Using this `kustomization.yaml`:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: datahub-prerequisites
    releaseName: datahub-prerequsites
    repo: https://helm.datahubproject.io/
    version: 0.1.13
  - name: datahub
    releaseName: datahub
    repo: https://helm.datahubproject.io/
    version: 0.4.39
    valuesInline:
      global:
        sql:
          datasource:
            username:
              secretRef: foo
              secretKey: bar
```

the error can be observed.

**Expected behavior**
Templates seem to indicate that it should be possible to set the username by secret, like here:
- https://github.com/acryldata/datahub-helm/blob/datahub-0.4.39/charts/datahub/subcharts/datahub-gms/templates/deployment.yaml#L152-L159

These PR also indicate that this should be supported:
- https://github.com/acryldata/datahub-helm/pull/291
- https://github.com/acryldata/datahub-helm/pull/380
