### ISSUE TITLE
Set "Try New User Experience" to TRUE by Default for All Users

### ISSUE THREAD

**Issue by amzar96** [acryldata/datahub-helm#558]
As an admin, how can I set the "Try New User Experience" option to TRUE by default for all users in the Datahub?

**Comment by amzar96** [comment]
<img width="1791" alt="Image" src="https://github.com/user-attachments/assets/e21e6167-6799-4053-9bf0-d4fafb2e5d38" />

**Comment by amzar96** [comment]
Solved. Thanks to [Jackson - Slack member](https://datahubspace.slack.com/archives/CV2UXSE9L/p1740556425421039?thread_ts=1740536665.705699&cid=CV2UXSE9L).

you can list these under the datahub-gms configuration in the helm chart
```yaml
extraEnvs:
  - name: THEME_V2_ENABLED
    value: "true"
  - name: THEME_V2_DEFAULT
    value: "true"
  - name: THEME_V2_TOGGLEABLE
    value: "false"
```
